@host=http://localhost:5275

POST {{host}}/api/auth/login
Content-Type: application/json

{
    "email": "jmedina@email.com",
    "password": "UnsafePassword1234@"
}

###

POST {{host}}/api/auth/login
Content-Type: application/json

{
    "email": "jmedina2@email.com",
    "password": "UnsafePassword1234@"
}