@host=http://localhost:5275

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Jason",
    "lastName": "Medina",
    "email": "jmedina@email.com",
    "role": "admin",
    "password": "UnsafePassword1234@"
}

###

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Jason2",
    "lastName": "Medina2",
    "email": "jmedina2@email.com",
    "role": "employee",
    "password": "UnsafePassword1234@"
}

### invalid request

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Jason3",
    "lastName": "Medina3",
    "email": "jmedina3@email.com",
    "role": "kekew",
    "password": "UnsafePassword1234@"
}
