@host=http://localhost:5275
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YTM5NTZlOC1kYmRiLTRhODgtYWI2Zi1iNjcxMjhmMGEwYzciLCJnaXZlbl9uYW1lIjoiSmFzb24iLCJmYW1pbHlfbmFtZSI6Ik1lZGluYSIsImp0aSI6IjYzYjhhOGQ3LTFiZTgtNDIxNy05ZmVlLWY4MGExNDZmYzJmMCIsIlJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMzYwMTIwOSwiaXNzIjoibTRkcmlhbiIsImF1ZCI6Im00ZHJpYW4ifQ.76CkyxgUbYTBhCoeATBv1cx-zWdSLeglf3ttMCU8e2E
@tokenEmployee=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0YmY5MzAxMi1mNGRlLTRmY2MtOTllMy03NmNiMzA5OTRiNTkiLCJnaXZlbl9uYW1lIjoiSmFzb24yIiwiZmFtaWx5X25hbWUiOiJNZWRpbmEyIiwianRpIjoiZjAwMTI3ZWUtZjQzYy00ZjBmLTg4ZDktOTM2NTNiYzFiN2RjIiwiUm9sZSI6ImVtcGxveWVlIiwiZXhwIjoxNzIzNTk4NDYzLCJpc3MiOiJtNGRyaWFuIiwiYXVkIjoibTRkcmlhbiJ9.C60ze2Js9QpagjISsVqorz7fRUKFdWXjC-qoYH7i0pw
@deskId=1

POST {{host}}/api/desks/Office2
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "LocationName" : "Office2",
    "UserEmail" : "randomGuy@email.com",
    "Available" : false,
    "StartDate" : "2024-08-20T08:00:00Z",
    "EndDate": "2024-08-21T10:00:00Z"
}

###

GET {{host}}/api/desks/all
Authorization: Bearer {{token}}}
Content-Type: application/json

{

}

###

GET {{host}}/api/desks/{{deskId}}
Authorization: Bearer {{token}}}
Content-Type: application/json

{

}

###

PUT /api/desks/reservation/{{deskId}}
Authorization: Bearer {{token}}}
Content-Type: application/json

{
    "DeskId" : "{{deskId}}",
    "Available" : true,
    "StartDate" : "{{ 2024-08-20 }}T{{ 08:00:00 }}Z",
    "EndDate": "{{ 2024-08-21 }}T{{ 10:00:00 }}Z"
}

###

PUT /api/desks/reservation/admin/{{deskId}}
Authorization: Bearer {{tokenEmployee}}}
Content-Type: application/json

{
    "DeskId" : "{{deskId}}",
    "UserEmail": "jmedina2@email.com",
    "Available" : false,
    "StartDate" : "{{ 2024-08-20 }}T{{ 08:00:00 }}Z"
}

###

DELETE {{host}}/api/desks/{{deskId}}
Authorization: Bearer {{token}}}
Content-Type: application/json

{
    "Id" : "{{deskId}}"
}