@host=http://localhost:5275
@tokenAdmin=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiZDZiZmFhZC1kYjA2LTRmYmEtYWE1OC00YWExNDc4Zjk0MmUiLCJnaXZlbl9uYW1lIjoiSmFzb24iLCJmYW1pbHlfbmFtZSI6Ik1lZGluYSIsImp0aSI6IjMzNzExMWJkLTQ1OGQtNDk2MC05OWIzLTU0ZGMwMzE4YjJkYSIsIlJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMzYwNDUzOSwiaXNzIjoibTRkcmlhbiIsImF1ZCI6Im00ZHJpYW4ifQ.E5suDTqyXUsUWJh1RPzlSogVyZn-YWHvhlBhQPE5rDA
@tokenEmployee=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmMzZjY2FiOS01OTM4LTRlYTItYWMwZS00ZTUxMmNmNjBkYzgiLCJnaXZlbl9uYW1lIjoiSmFzb24yIiwiZmFtaWx5X25hbWUiOiJNZWRpbmEyIiwianRpIjoiMjZiYmIyNTMtMjZlZC00ZGRmLTg3MTYtY2IxNDE2YzI0MzQxIiwiUm9sZSI6ImVtcGxveWVlIiwiZXhwIjoxNzIzNjA0NTg5LCJpc3MiOiJtNGRyaWFuIiwiYXVkIjoibTRkcmlhbiJ9.KnKeTiFyxsBi0joIt4l9fOzn-UOZoYrE8ZzpF4f9zT8

POST {{host}}/api/locations
Authorization: Bearer {{tokenAdmin}}
Content-Type: application/json

{
    "name": "Office1",
    "description": "Office with multiple heaters"
}

###

POST {{host}}/api/locations
Authorization: Bearer {{tokenAdmin}}
Content-Type: application/json

{
    "name": "Office2",
    "description": ""
}

### Bad Request

POST {{host}}/api/locations
Authorization: Bearer {{tokenAdmin}}
Content-Type: application/json

{
    "name": "",
    "description": ""
}

### get all locations

GET {{host}}/api/locations/all
Authorization: Bearer {{tokenAdmin}}
Content-Type: application/json

{

}

### get desks from location

GET {{host}}/api/locations/desks/Office2
Authorization: Bearer {{tokenEmployee}}
Content-Type: application/json

{
    "Name" : "Office2"
}

###

PUT {{host}}/api/locations/Office2
Authorization: Bearer {{tokenAdmin}}
Content-Type: application/json

{
    "ChangedName": "Office12",
    "description": "Office with multiple AC units"
}

###

DELETE {{host}}/api/locations/Office2
Authorization: Bearer {{tokenAdmin}}
Content-Type: application/json

{
    "Name": "Office2"
}
